name: Generate Version Pages

on:
  push:
    branches:
      - main

jobs:
  generate-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install axios

      - name: Generate Version Pages
        run: |
          node scripts/generate-pages.js ${{ github.repository }} ${{ github.sha }}

      - name: Commit Version Pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Generate version pages"
          git push
